### ISSUE TITLE
SystemTap

### ISSUE THREAD

**Issue by 44iCdnz** [ChessMax/awesome-programming-languages#104]
https://sourceware.org/systemtap/

**Comment by ChessMax** [comment]
I'm not sure but it doesn't look like a PL.

**Comment by 44iCdnz** [comment]
> 

It's in the same class as DTrace. They are tracing frameworks. But they have their own languages to do so:

https://en.wikipedia.org/wiki/DTrace#See_also

This is an example of DTrace scripts: https://docs.oracle.com/cd/E18752_01/html/819-5488/gcfqr.html

**Comment by 44iCdnz** [comment]
It's fine to not include them as they are not programming language in common sense.
