### ISSUE TITLE
The Slang Programming Language (formerly known as ObjectiveScript)

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#127]
https://github.com/slang-lang/slang

**Comment by 3oheicrw-alter-ego** [comment]
Reopen to close as completed. The language is currently in the transition from ObjectiveScript to Slang. Let it alone. Maybe someday someone will submit a ticket about adding it when the transition is completed. But now I think it shouldn't be added.

**Comment by 3oheicrw-alter-ego** [comment]
He said it's production ready: https://github.com/slang-lang/slang/issues/4#issuecomment-1293209553

**Comment by ChessMax** [comment]
Thanks!
