### ISSUE TITLE
sdlBasic

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#130]
https://sourceforge.net/projects/sdlbasic/

**Comment by 3oheicrw-alter-ego** [comment]
https://www.sdlbasic.altervista.org/main/index.html

**Comment by 3oheicrw-alter-ego** [comment]
It's on this list: https://www.thefreecountry.com/compilers/basic.shtml

**Comment by 3oheicrw-alter-ego** [comment]
Virustotal said it's safe. Reopen.

**Comment by ChessMax** [comment]
Generic link to awesome-basic curated list added.
