### ISSUE TITLE
nuBASIC

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#132]
https://github.com/eantcal/nubasic

**Comment by 3oheicrw-alter-ego** [comment]
Prebuilt binaries on sourceforge nubasic-ide-1.51-setup_x64.zip extracted as setup-vs64.exe (so it seems require Visual Studio?), virustotal said setup-vs64.exe is safe.

**Comment by 3oheicrw-alter-ego** [comment]
Why it's 64 bit but install to `Program Files (x86)`?

Default path to install by setup: `C:\Program Files (x86)\nuBASIC (x64)`

**Comment by ChessMax** [comment]
Generic link to awesome-basic curated list added.
