### ISSUE TITLE
JustBASIC/LibertyBASIC

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#134]
https://www.justbasic.com/index.html

https://www.libertybasic.com/

**Comment by 3oheicrw-alter-ego** [comment]
It has a wiki entry: https://en.wikipedia.org/wiki/Liberty_BASIC

I downloaded and installed it, seems to be safe.

**Comment by 3oheicrw-alter-ego** [comment]
Just to note that JustBASIC runs perfectly in Wine on Linux too. I didn't try with LibertyBASIC.

**Comment by iahung** [comment]
Don't pollute this list with BASIC dialects!

BASIC languages have their own list! It's already part of that list: https://github.com/JohnBlood/awesome-basic

**Comment by ChessMax** [comment]
Generic link to awesome-basic curated list added.
