### ISSUE TITLE
BBC BASIC

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#135]
This is free and open source edition: https://www.bbcbasic.co.uk/bbcsdl/index.html

BB4W is commercial.

**Comment by 3oheicrw-alter-ego** [comment]
It has a ridiculous memory limitation, quoted from the page above:

> Up to 256 Megabytes of memory (16 Mbytes in the in-browser edition) is provided for the user's program, data and stack (subject to sufficient RAM being available). Unlike some older versions of BASIC, you won't suffer the frustration of running out of memory! Line numbers are optional. 

But I think it's safe? At least it's from the [BBC](https://en.wikipedia.org/wiki/BBC)?

It has a wiki entry: https://en.wikipedia.org/wiki/BBC_BASIC

**Comment by iahung** [comment]
Don't pollute this list with BASIC dialects!

BASIC languages have their own list! It's already part of that list: https://github.com/JohnBlood/awesome-basic

**Comment by ChessMax** [comment]
Generic link to awesome-basic curated list added.
