### ISSUE TITLE
nuBScript

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#138]
https://github.com/eantcal/nubscript

**Comment by 3oheicrw-alter-ego** [comment]
We already have nuBASIC: https://github.com/ChessMax/awesome-programming-languages/issues/132

**Comment by 3oheicrw-alter-ego** [comment]
Reopen to close as completed.

**Comment by ChessMax** [comment]
Generic link to awesome-basic curated list added.
