### ISSUE TITLE
please add pocketlang

### ISSUE THREAD

**Issue by ThakeeNathees** [ChessMax/awesome-programming-languages#14]
[pocketlang](https://github.com/ThakeeNathees/pocketlang) (https://github.com/ThakeeNathees/pocketlang) - A lightweight, fast embeddable scripting language. Features classes, first class functions, closures, REPL, garbage collection, fiber based concurrency, and more.

And here are some interesting languages not in the list:
lua : https://github.com/lua/lua
jannet : https://github.com/janet-lang/janet
red: https://github.com/red/red

**Comment by ChessMax** [comment]
Red lang has been already added some time ago. I've added other lang. Thanks👍
