### ISSUE TITLE
Monkey 2

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#140]
https://monkeycoder.co.nz/

**Comment by 3oheicrw-alter-ego** [comment]
Newsite: https://blitzresearch.itch.io/monkey2

**Comment by 3oheicrw-alter-ego** [comment]
Source code: https://github.com/blitz-research/monkey2

**Comment by 3oheicrw-alter-ego** [comment]
Seems unrelated to this: https://monkeylang.org/ But I could be wrong.

**Comment by 3oheicrw-alter-ego** [comment]
Monkey2-v2018.09.exe Virustotal 1/60, 1 could be false positive.

**Comment by ChessMax** [comment]
Thanks!
