### ISSUE TITLE
Dark-Basic-Pro

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#142]
https://github.com/TheGameCreators/Dark-Basic-Pro

**Comment by 3oheicrw-alter-ego** [comment]
https://www.thegamecreators.com/product/dark-basic-pro-open-source

**Comment by 3oheicrw-alter-ego** [comment]
https://en.wikipedia.org/wiki/The_Game_Creators

**Comment by 3oheicrw-alter-ego** [comment]
It's on this list: https://www.thefreecountry.com/compilers/basic.shtml

**Comment by ChessMax** [comment]
Thanks!
