### ISSUE TITLE
POWER-KI

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#148]
https://github.com/POWER-KI/POWER-KI

**Comment by 3oheicrw-alter-ego** [comment]
From the description it's an interesting language, but I'm not sure if it's safe or not. It's available on Softpedia. The homepage of it is not https. This makes me afraid.

**Comment by 3oheicrw-alter-ego** [comment]
Virustotal said it's safe, will reopen.

**Comment by ChessMax** [comment]
Thanks!
