### ISSUE TITLE
Please add PascalABC.NET

### ISSUE THREAD

**Issue by shlwapi** [ChessMax/awesome-programming-languages#30]
https://github.com/pascalabcnet/pascalabcnet

Latest release could be downloaded from the homepage: http://pascalabc.net/en/

I have no idea why they have not yet upgraded the connection to https.

**Comment by ChessMax** [comment]
Thanks!

**Comment by 3oheicrw** [comment]
@ChessMax The entry for PascalABC.NET has format error, it needs to be fixed.
