### ISSUE TITLE
Biscuit

### ISSUE THREAD

**Issue by guckstift** [ChessMax/awesome-programming-languages#310]
The Biscuit Language (BL) is simple imperative programming language using LLVM backend implemented in C. Biscuit is designed to be simple, fast and explicit. Language syntax is inspired by JAI.

http://biscuitlang.org/
https://github.com/travisdoor/bl

# Features
* Strongly typed.
* Embedded rich runtime type information.
* Polymorphic functions and structures (generics).
* Simple structure inheritance.
* Compile-time execution (experimental).
* Compile-time function arguments; allow passing types as values (experimental).
* C ABI compatible (C library functions can be directly called).
* Runtime debugging is possible in Visual Studio/gdb/lldb.
* Explicit function overloading.
* Integrated build system.
* Module management.
* Unit testing system.
* Automatic documentation generation.
* Defer statement.
* Multiple return values.
* Custom memory allocators.
* Basic support for game development via extra packages.
* Supports Windows, Linux and macOS.
* Nested functions.
* Clean and simple JAI-like syntax.
And more...

**Comment by ChessMax** [comment]
Thanks!
