### ISSUE TITLE
hook-lang

### ISSUE THREAD

**Issue by 1997tn** [ChessMax/awesome-programming-languages#321]
https://github.com/fabiosvm/hook-lang

**Comment by fabiosvm** [comment]
Lol I like that language! ;) I could do a Pull Request, what do you think, @ChessMax?

**Comment by ChessMax** [comment]
PR will be awesome. Otherwise I will add it to the list myself soon. Thanks 👍

**Comment by fabiosvm** [comment]
PR #322

**Comment by ChessMax** [comment]
Merged. Thanks!

**Comment by fabiosvm** [comment]
Thank you!
