### ISSUE TITLE
Clarify inclusion criteria

### ISSUE THREAD

**Issue by FeldrinH** [ChessMax/awesome-programming-languages#400]
It would be nice to more explicitly clarify the inclusion criteria for programming languages.
Specifically, I had the following questions:
* What is the policy on languages where development has stopped? Should they be submitted for inclusion? Should already listed languages be removed if develpment has stopped?
* What is considered a 'programming language'? I notice that Typst, Melody and MarkovJunior, which are fairly specialized languages, are included, so I assume the definition is quite broad.

**Comment by ChessMax** [comment]
Thanks for your questions. Good points, but I don't sure I have answers to them.

> What is the policy on languages where development has stopped? Should they be submitted for inclusion?

I think it should depend on language itself. Is there a value in adding this language to the list? If the answer it yes, then you are welcome to submit it.

> Should already listed languages be removed if develpment has stopped?

The answer is partially the same as in the previous question. Also, I think to add some kind of tag, so it would be possible to mark the language without explicitly removing it.

> What is considered a 'programming language'?

It's also difficult to answer to this question. It seems that languages like Typst, Melody and MarkovJunior should be marked with DSL tag? Or something. So you will be able to filter out languages like these if you are not interested in them.

If you have any suggestions, I'm all ears. Thanks in advance.
