### ISSUE TITLE
Remove Prompto?

### ISSUE THREAD

**Issue by FeldrinH** [ChessMax/awesome-programming-languages#414]
Prompto's official website (http://www.prompto.org/) is down. Since most of the Prompto repos link to it for prebuilt releases and documentation this makes it difficult to use Prompto for anything. The most recent commits seem to be made in late 2022, so presumably the project is currently unmaintained.

**Comment by ChessMax** [comment]
The source code is available on github, so let it be, then.

**Comment by 3oheicrw-ver2** [comment]
Back online again: https://www.prompto.org/ (upgraded to https)
