### ISSUE TITLE
Your list in my Google Sheets

### ISSUE THREAD

**Issue by axtens** [ChessMax/awesome-programming-languages#433]
I'm happy to share my Google Sheets version of your list with you so you can see what I'm adding. I do a lot of Google Sheets and Google Apps Script for my day job. I have a couple of ideas on how to go from sheet to site. Send me an email address.

**Comment by axtens** [comment]
Let me know if this doesn't work. If you have a gmail account it should.

https://script.google.com/macros/s/AKfycbyI1V4POLmXN8EFrXP-WQ92yH3i08kofD4lC1MV2Ljc1xnE9L4LXoAgt1sbHy8QQIov/exec?letter=S

Any other letter A-Z should work

**Comment by axtens** [comment]
https://script.google.com/macros/s/AKfycbyI1V4POLmXN8EFrXP-WQ92yH3i08kofD4lC1MV2Ljc1xnE9L4LXoAgt1sbHy8QQIov/exec?readme=1 now generates a full README.md with updated counts from the spreadsheet

**Comment by ChessMax** [comment]
I don't think it's a good idea to share links like that, cause I've tried to open it, and it says it unverified and dangerous. Why you couldn't just add a link to your spreadsheet file? I will just add it to see also section.

**Comment by axtens** [comment]
Fair comment. Shall have a think about that

**Comment by axtens** [comment]
Okay, removed. Using it for myself only.
