### ISSUE TITLE
BaCon - BASIC to C converter

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#95]
https://www.basic-converter.org/

**Comment by 44iCdnz** [comment]
It's rather a compiler isn't it? But it has it own BASIC dialect. I don't know for sure if it should be there or not.

**Comment by 44iCdnz** [comment]
Let's the maintainer decided this for me.

**Comment by ChessMax** [comment]
I'm not sure what to do with it. It's seems that it's not a dialect.

**Comment by 44iCdnz** [comment]
> I'm not sure what to do with it. It's seems that it's not a dialect.

It has it own extensions to the BASIC language (so do other BASICs). This making it not standard BASIC (BASIC has no standard anyway, there will always be dialects with the original Microsoft products could be viewed as the references). btw it's fine to not including it though.
