### ISSUE TITLE
Vishap Oberon

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-programming-languages#98]
https://github.com/vishaps/voc

**Comment by 44iCdnz** [comment]
This is controversial. It should be classified as a compiler or a programming language? Let's the maintainer of this list decide.

**Comment by ChessMax** [comment]
Yea, it's very controversial. I'm not sure what to do with it.

**Comment by 44iCdnz** [comment]
> Yea, it's very controversial. I'm not sure what to do with it.

I vote to not include it, so you should remove OfrontPlus from the list too. They are both compilers!
