### ISSUE TITLE
OfrontPlus

### ISSUE THREAD

**Issue by 44iCdnz** [ChessMax/awesome-programming-languages#99]
https://github.com/Oleg-N-Cher/OfrontPlus

**Comment by 44iCdnz** [comment]
This is controversial. It should be classified as a compiler or a programming language? Let's the maintainer of this list decide.

**Comment by ChessMax** [comment]
Thanks!

**Comment by 44iCdnz** [comment]
> Thanks! Yea, this is very controversial. I'm not sure what to do. May be it's better to introduce another list? But I'm not sure we need such a list.

There is a mistake here. You added it to the list!

https://github.com/ChessMax/awesome-programming-languages/commit/fc2f84b633c2ac17881c34dafbb8564d9d8fb2d9

**Comment by 44iCdnz** [comment]
If Vishap Oberon not added, then this shouldn't be added too! They are both compilers!

https://github.com/ChessMax/awesome-programming-languages/issues/98

**Comment by 44iCdnz** [comment]
@ChessMax Have a look at them. They are compilers too?

https://github.com/ChessMax/awesome-programming-languages/issues/78

https://github.com/ChessMax/awesome-programming-languages/issues/77

**Comment by 44iCdnz** [comment]
Revisit some old things added.

Isn't it just an Objective C compiler? It uses a modified LLVM Clang and it seems it introduced nothing new to the Objective C language too?

https://github.com/ChessMax/awesome-programming-languages/issues/49

But we could view as somewhat different. It's another implementation of Objective C compared to Apple's Objective C and GNUStep's Objective C.

Aren't these two compilers just implement the same Modula-2 language?

https://github.com/ChessMax/awesome-programming-languages/issues/38

https://github.com/ChessMax/awesome-programming-languages/issues/37

They are definitely have different headers set, so does different C/C++ compilers have different headers set (e.g: MSVC has a different set of headers compared to GCC even though both of them are conformant to ISO C/C++ standard). Does that alone make them dialects of C/C++? The same discipline applied in this situation.

**Comment by 44iCdnz** [comment]
Isn't it just an Objective C compiler? It uses a modified LLVM Clang and it seems it introduced nothing new to the Objective C language too?

https://github.com/ChessMax/awesome-programming-languages/issues/49

But we could view as somewhat different. It's another implementation of Objective C compared to Apple's Objective C and GNUStep's Objective C.

**Comment by 44iCdnz** [comment]
Aren't these two compilers just implement the same Modula-2 language?

https://github.com/ChessMax/awesome-programming-languages/issues/38

https://github.com/ChessMax/awesome-programming-languages/issues/37

They are definitely have different headers set, so does different C/C++ compilers have different headers set (e.g: MSVC has a different set of headers compared to GCC even though both of them are conformant to ISO C/C++ standard). Does that alone make them dialects of C/C++? The same discipline applied in this situation.

**Comment by 44iCdnz** [comment]
The list already has Eiffel lang added but it's ISE Eiffel (https://www.eiffel.org/). Eiffel is a standardized language (http://www.ecma-international.org/publications/standards/Ecma-367.htm) that has many implementations. ISE Eiffel is just the reference implementation. Gobo Eiffel is just another implementation.

https://github.com/ChessMax/awesome-programming-languages/issues/61

So should Gobo Eiffel be added? Gobo Eiffel has a different set of headers compared to ISE Eiffel. Does an implementation considered as a dialect if it's different enough?

I found you added a bunch of Scheme and Lisp dialects. Sometimes they are not different enough to be a dialect, they are just implementations of different Scheme and Lisp standards (e.g: Scheme R6RS vs Scheme R7RS). So you are somewhat relaxed about that. Does that apply in this situation too?

The list is so large. It's based on contributions without any disciplines stated. Revisiting the list is very hard to do. It seems you are unexpected to see it's growing that big.

**Comment by 44iCdnz** [comment]
Just realized Lisp has it own dialects list: https://github.com/dundalek/awesome-lisp-languages

**Comment by 3oheicrw** [comment]
Yeah, Gobo Eiffel is more a compiler than a programming language.

**Comment by 3oheicrw** [comment]
@ChessMax Should you merge the entry of GNU Modula-2 and ADW Modula-2 into just Modula 2? It's up to you to decide to provide link to GNU Modula-2 or ADW Modula-2.
